#! /bin/sh
xrandr --output DVI-D-1 --mode 1920x1080 --rate 144&
polybar main_bar&
feh --bg-center .wp.png&
compton --config /home/prashant/.compton.conf&
 mopidy&
redshift -l -35.3:149&


sxhkd &

bspc monitor -d one two three four five six seven eight nine ten
bspc config top_padding        10
bspc config bottom_padding     10
bspc config left_padding       10
bspc config right_padding 10
bspc config border_width         2
bspc config window_gap          25
bspc config normal_border_color "#312842"
bspc config focused_border_color "#c16772"
bspc config urgent_border_color "#c16772"
bspc config presel_border_color "#ffeefc"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a MuPDF state=floating
bspc rule -a Termite:stick state=floating sticky=on center
bspc rule -a Termite:stick1 state=floating sticky=on
bspc rule -a Termite:stick2 state=floating sticky=on
bspc rule -a Termite:float state=floating
#bspc rule -a Termite:term state=tiled
xsetroot -cursor_name left_ptr&
