#! /bin/sh
xrandr --output HDMI-1 --right-of DVI-D-1 --mode 2560x1440 --pos 2560x0 --rotate normal --output DVI-D-1 --primary --mode 2560x1440 --pos 0x0 --rotate normal
nitrogen --restore&
compton --config /home/prashant/.compton.conf&
mopidy&
xrdb ~/.Xresources&
#polybar bar3&
#polybar bar4&
dunst&

bspc monitor DVI-D-1 -d one two three four five
bspc monitor HDMI-1 -d six seven eight nine ten
bspc config top_padding        10
bspc config bottom_padding     10
bspc config left_padding       10
bspc config right_padding      10
bspc config border_width         4
bspc config window_gap          20
bspc config normal_border_color "#42423d"
bspc config focused_border_color "#eee4e5"
bspc config presel_border_color "#ffbec9"
bspc config split_ratio          0.52
bspc config click_to_focus 	button1
bspc config swallow_first_click	true
bspc config pointer_follows_focus	true
bspc config pointer_follows_monitor	true
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config paddingless_monocle	true

bspc rule -a mpv state=floating
bspc rule -a "*:sxiv" state=floating
bspc rule -a URxvt:stick state=floating sticky=on center
bspc rule -a URxvt:stick1 state=floating sticky=on
bspc rule -a URxvt:stick2 state=floating sticky=on
bspc rule -a URxvt:float state=floating
bspc rule -a URxvt:cal state=floating sticky=on
bspc rule -a Steam:"Friends List" state=floating
bspc rule -a polybar layer=above
bspc rule -a "dotnet" state=floating

redshift -l -35.3:149&
xsetroot -cursor_name left_ptr&
export PATH=/home/prashant/.local/bin:$PATH
#i3lock
