#! /bin/sh
xrandr --output DVI-D-1 --mode 1920x1080 --rate 144&
#polybar main&
#feh --bg-tile .w.gif&
xwinwrap -ov -g 1920x1080+0+0 -- mpv -wid WID ~/.gifs/usable/io.mp4 --no-osc --no-osd-bar --loop-file --player-operation-mode=cplayer --no-input-default-bindings --hwdec --log-file=/home/prashant/.mpvlog.log&
compton --config /home/prashant/.compton.conf&
 mopidy&
redshift -l -35.3:149&
xrdb ~/.Xresources
dunst&
sxhkd &

bspc monitor -d one two three four five six seven eight nine ten
bspc config top_padding        10
bspc config bottom_padding     10
bspc config left_padding       10
bspc config right_padding      10
bspc config border_width         5
bspc config window_gap          50
bspc config normal_border_color "#42423d"
bspc config focused_border_color "#eee4e5"
bspc config urgent_border_color "#eee4e5"
bspc config presel_border_color "#ffbec9"
#bspc config border_radius	10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
#bspc rule -a MuPDF state=floating
bspc rule -a Termite:stick state=floating sticky=on center
bspc rule -a Termite:stick1 state=floating sticky=on
bspc rule -a Termite:stick2 state=floating sticky=on
bspc rule -a Termite:float state=floating
bspc rule -a URxvt:stick state=floating sticky=on center
bspc rule -a URxvt:stick1 state=floating sticky=on
bspc rule -a URxvt:stick2 state=floating sticky=on
bspc rule -a URxvt:float state=floating
bspc rule -a Steam:"Friends List" state=floating

xsetroot -cursor_name left_ptr&
bash /home/prashant/.lock.sh
