#!/bin/sh
#
# ufetch-arch - tiny system info for arch

## INFO

# user is already defined
host="$(hostname)"
os='Arch Linux'
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pacman -Q | wc -l)"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE:'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE:'
		WM="${DESKTOP_SESSION}"
	elif [ -f "${HOME}/.xinitrc" ]; then
		envtype='WM:'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM:'
fi

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${cyan}"		# labels
nc="${reset}${cyan}"		# user and hostname
ic="${reset}${white}"		# info
c0="${reset}${cyan}"		# first color
c1="${reset}${cyan}"			# second color

## OUTPUT

cat <<EOF

${c0}        /\        ${nc}whats${ic} ${nc}good${reset}
${c0}       /^^\       ${lc}os  ${ic}arch linux${reset}
${c0}      /\   \      ${lc}wm  ${ic}bspwm${reset}
${c0}     /  ${c1}__  \     ${lc}terminal  ${ic}termite${reset}
${c1}    /  (  )  \    ${lc}music player  ${ic}ncmpcpp${reset}
${c1}   / __|  |__\\\\   ${lc}shell  ${ic}zsh${reset}
${c1}  ///        \\\\\  ${lc}file browser  ${ic}ranger${reset}

EOF
