#! /bin/sh
xrandr --output DVI-D-1 --mode 1920x1080 --rate 144&
feh --bg-fill ~/.wp2.jpg&
compton --config /home/prashant/.compton.conf&
mopidy&
redshift -l -35.3:149&
xrdb ~/.Xresources&
polybar bar3&
dunst&

bspc monitor -d one two three four five six seven eight nine ten
bspc config top_padding        55
bspc config bottom_padding     10
bspc config left_padding       10
bspc config right_padding      10
bspc config border_width         3
bspc config window_gap          20
bspc config normal_border_color "#42423d"
bspc config focused_border_color "#eee4e5"
bspc config presel_border_color "#ffbec9"
bspc config split_ratio          0.52

bspc rule -a mpv state=floating
bspc rule -a "*:sxiv" state=floating
bspc rule -a URxvt:stick state=floating sticky=on center
bspc rule -a URxvt:stick1 state=floating sticky=on
bspc rule -a URxvt:stick2 state=floating sticky=on
bspc rule -a URxvt:float state=floating
bspc rule -a Steam:"Friends List" state=floating
bspc rule -a "polybar" layer=above
bspc rule -a "dotnet" state=floating

xsetroot -cursor_name left_ptr&
xsetwacom set 9 Area 0 0 6000 6000&
